// <auto-generated />
namespace Produktkatalog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Multiline_Annotation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Multiline_Annotation));
        
        string IMigrationMetadata.Id
        {
            get { return "201606081231241_Multiline_Annotation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
